name: strchive
channels:
  - bioconda
  - conda-forge
dependencies:
  - pandas
  - numpy
  - biopython
  - defopt
  - snakemake
  - jsbeautifier
  - statsmodels
  - plotly
  - r-essentials
  - r-jsonlite
  - r-dplyr
  - r-rentrez
  - r-easypubmed
  - r-stringr
  - r-purrr
  - pip
  - pip:
      - manubot
  - python=3.12
