name: strchive
channels:
  - bioconda
  - conda-forge
dependencies:
  - pandas
  - numpy
  - biopython
  - defopt
  - snakemake=7.25.0
  - jsbeautifier
  - statsmodels
  - plotly
  - zlib
  - r-essentials
  - r-base
  - r-jsonlite
  - r-dplyr
  - r-rentrez
  - r-easypubmed
  - r-stringr
  - r-purrr
  - pysam
  - htslib
  - bedtools
  - nodejs
  - pyliftover
  - pip
  - pip:
      - manubot
  - python=3.12
