configfile: '../data/config.yaml'
in_json: str = config["input_file"]
base_dir: str = config["base_directory"]

### IMPORTS ###
import os
import re

# Wildcard constraints; should all be alphanumeric
wildcard_constraints:
    base_dir = base_dir

rule all:
    input:
        # Check loci
        expand("{base_dir}check-loci.json", base_dir = base_dir),
        # Citations
        expand("{base_dir}STRchive-citations.json", base_dir = base_dir),
        # TRGT bed files
        expand("{base_dir}hg38.STRchive-disease-loci.TRGT.bed", base_dir = base_dir),
        expand("{base_dir}hg19.STRchive-disease-loci.TRGT.bed", base_dir = base_dir),
        expand("{base_dir}T2T-chm13.STRchive-disease-loci.TRGT.bed", base_dir = base_dir),
        # Extended BED files
        expand("{base_dir}hg38.STRchive-disease-loci.bed", base_dir = base_dir),
        expand("{base_dir}hg19.STRchive-disease-loci.bed", base_dir = base_dir),
        expand("{base_dir}T2T-chm13.STRchive-disease-loci.bed", base_dir = base_dir),

        # To do: add STRchive version number to all the bed files?

rule check_loci:
    input:
        in_json = in_json
    output:
        check = temp("{base_dir}check-loci.json")
    shell:
        """
        python check-loci.py {input.in_json} 2> {output.check}
        """

rule retrieve:
    input:
        in_json = in_json,
        lit_dir = "{base_dir}literature",
        script_path = "get-literature.R",
        check = "{base_dir}check-loci.json"
    output:
        citations = temp("{base_dir}citations-tmp.json")
    shell:
        """
        Rscript {input.script_path} {input.in_json} {input.lit_dir} {output.citations}
        """

# Note, this currently takes hours to run
rule manubot:
    input:
        citations = "{base_dir}citations-tmp.json",
        check = "{base_dir}check-loci.json"
    output:
        results = "{base_dir}STRchive-citations.json"
    shell:
        """
        python run-manubot.py {input.citations} {output.results}
        """

rule TRGT_hg38:
    input:
        in_json = in_json,
        check = "{base_dir}check-loci.json"
    output:
        results = "{base_dir}hg38.STRchive-disease-loci.TRGT.bed"
    shell:
        """
        python make-catalog.py -f TRGT -g hg38 {input.in_json} {output.results}
        """

rule TRGT_hg19:
    input:
        in_json = in_json,
        check = "{base_dir}check-loci.json"
    output:
        results = "{base_dir}hg19.STRchive-disease-loci.TRGT.bed"
    shell:
        """
        python make-catalog.py -f TRGT -g hg19 {input.in_json} {output.results}
        """

rule TRGT_T2T:
    input:
        in_json = in_json,
        check = "{base_dir}check-loci.json"
    output:
        results = "{base_dir}T2T-chm13.STRchive-disease-loci.TRGT.bed"
    shell:
        """
        python make-catalog.py -f TRGT -g T2T {input.in_json} {output.results}
        """

rule bed_hg38:
    input:
        in_json = in_json,
        check = "{base_dir}check-loci.json"
    output:
        results = "{base_dir}hg38.STRchive-disease-loci.bed"
    shell:
        """
        python make-catalog.py -f bed -g hg38 {input.in_json} {output.results}
        """

rule bed_hg19:
    input:
        in_json = in_json,
        check = "{base_dir}check-loci.json"
    output:
        results = "{base_dir}hg19.STRchive-disease-loci.bed"
    shell:
        """
        python make-catalog.py -f bed -g hg19 {input.in_json} {output.results}
        """

rule bed_T2T:
    input:
        in_json = in_json,
        check = "{base_dir}check-loci.json"
    output:
        results = "{base_dir}T2T-chm13.STRchive-disease-loci.bed"
    shell:
        """
        python make-catalog.py -f bed -g T2T {input.in_json} {output.results}
        """